### ISSUE TITLE
Include dependencies of real libhsl distribution in the binary release

### ISSUE THREAD

**Issue by metab0t** [cvanaret/Uno#79]
The `libhsl.so/dll` in `HSL_jll` downloaded from https://licences.stfc.ac.uk/product/libhsl cannot be used directly because they have more dependencies than the dummy one.

This is the dependency list of real `HSL_jll` package:
```toml
[deps]
MPICH_jll = "7cb0a576-ebde-5e09-9194-50597f1243b4"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
METIS_jll = "d00139f3-1899-568f-a2f0-47f597d42d70"
OpenBLAS32_jll = "656ef2d0-ae68-5445-9ca0-591084a874a2"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
MicrosoftMPI_jll = "9237b28f-5490-5468-be7b-bb81f5f5e6cf"
```

So maybe `MPICH_jll` and `MicrosoftMPI_jll` should be included in the binary release to make replacing HSL libraries easier?
